codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: 60..80
  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        target: 80%
        threshold: 5%
        if_ci_failed: error

comment:
  layout: "header, diff, flags, tree"
  require_changes: false
  behavior: default

ignore:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/coverage/**"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.integration.test.ts"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/*.d.ts"
  - "**/test-results/**"
  - "**/.next/**"
  - "**/.turbo/**"
  - "**/public/**"
  - "**/vite.config.ts"
  - "**/tailwind.config.cjs"
  - "**/postcss.config.js"
